### ISSUE TITLE
Program terminates on terminal resize

### ISSUE THREAD

**Issue by AObuchow** [datho7561/MonitorBacklight#1]
This is a cool project idea IMO :D 

Running it using Konsole 20.12.0 as my terminal emulator (on Linux), I encountered an issue where resizing the terminal window would terminate the application.

It'd be nice if the application could account for resizing :)

If further info is needed just let me know!

**Comment by AObuchow** [comment]
I'm currently working on a draft fix based on [this](https://stackoverflow.com/a/15450885)

**Comment by AObuchow** [comment]
I tried something like the following, but it doesn't seem to work.
``` C
#include <ncurses.h>
#include <signal.h>
#include <stdlib.h>

void resizeHandler(int sig) {
  // These environment variables are supposed to hold the terminal size, on Linux at least
  const char* linesStr = getenv("LINES");
  const char* columnsStr = getenv("COLUMNS");
  if (linesStr == NULL || columnsStr == NULL){
	 return;
  }
  
  
  int lines = atoi(linesStr);
  int columns = atoi(columnsStr);
  if (lines > 0 && columns > 0) {
       resizeterm(lines, columns);
       refresh();
  }
 
}

int main() {
  /*...*/
  initscr();

  /* Handle SIGWINCH signal on terminal resize */
  signal(SIGWINCH, resizeHandler);
  /*...*/
  
```
At the very least, adding a signal handler for SIGWINCH prevents the application from exiting on terminal resize. However, proper handling to resize the color being drawn to the terminal needs to be accounted for.

**Comment by datho7561** [comment]
Okay, I might take a look into this this evening. I think maybe making a dedicated exit key/key combo might also help.

**Comment by AObuchow** [comment]
@datho7561 I think so too 😎

**Comment by datho7561** [comment]
I ended up pushing a commit where `q` or `Ctrl+C` exits. It avoid signal handling. I tested under Konsole and gnome-terminal and it handled resizing.
